#!/usr/bin/with-contenv bash

# shellcheck shell=bash

set -e

while true; do

    cpu_usage=$(ps ax -o pcpu= | awk '{s+=$1}END{print s}')
    cpu_usage=${cpu_usage%.*}

    if (( cpu_usage > 100 )); then
        echo "Dying due to high cpu usage ($cpu_usage)"
        exit 1
    fi

    sleep 27s
done
